# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Sphinx documentation builder
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   version: "3.12"
   install:
   	- requirements: ./requirements.txt
